#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/gcc-4.2 -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch i386 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.3.sdk"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Sat Jul 16 15:51:03 EDT 2011"
#endif
